version: '3'
services:
  app:
    build: ./packages/ml_api
    volumes:
      - ./packages/ml_api:/app
    ports:
      - "192.168.99.100:5000:5000"    
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "192.168.99.100:6379:6379"
