version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "192.168.99.100:5000:5000"    
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  redis:
    image: "redis:alpine"
    ports:
      - "192.168.99.100:6379:6379"
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"