version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.3
  working_directory: ~/project



jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/project/packages/ml_api
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run tests 
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            tox -e py37


  
