version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/
    steps:
      - checkout:
          path: ~/packages/ml_api
      - run:
          name: Running tests 
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            tox -e py37


  
